[package]
name = "game-of-life"
edition = "2021"
version = "0.1.0"

[dependencies]
single_value_channel = "1.2.2"

[dependencies.minifb]
version = "0.27.0"
features = ["x11", "libc"]
default-features = false
